@startuml
title Activity Diagram 

start
:Вимірювання та аналіз рівня шуму в навколишньому середовищі;
if (Успішно?) then (Так)
  :На основі виміряного рівня шуму, система має аналізувати ці дані та надавати рекомендації для зменшення шуму;
  :Надання рекомендацій;
  if (Успішно?) then (Так)
    :Користувач отримує відповідь;
  else (Ні)
    :Повідомлення про помилку;
  endif
else (Ні)
  :Очікування відповіді;
endif
stop

@enduml
